#Target_name : Dependencies
#<TAB>Command

target : bookmanagement.c newbook.c displaybook.c searchbook.c deletebook.c bookmanagement.h
	gcc bookmanagement.c newbook.c displaybook.c searchbook.c deletebook.c -o all.out

run: target
	./all.out

clean:
	*/all.out